name: Security Patrol

on: [push, pull_request]

jobs:
  basic-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: action/checkout@v3

      - name: Say Hello
        uses: echo "The security Patrol is scanning commit ${{ github.sha }}..."

      - name: List files
        uses: ls -lah
